import Head from 'next/head'
import { getPropsForCategory, getMenuBySlug  } from '../lib/api'
import Header from '../components/header'
import Footer from '../components/footer'
import HomeFeatured from '../components/home-featured'
import FeaturedCategory from '../components/featured-category'
import Newsletter from '../components/newsletter'

export default function Home({ top, hardware, brands, navigationMenus }) {

    return (
        <>
            <Head>
                <title>Smart Home Starter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header menu={navigationMenus}/>
            <div className='container mt-14'>
                <HomeFeatured myArticles={top.edges} myCategory={'Featured'}/>
            </div>
                <div className='flex justify-center bg-black py-12'>
                    <div className='text-sky-600 w-80 text-2xl font-bold tracking-wider'>
                        Sign up for our newsletter for news, deals, and other stuff
                    </div>
                    <div className='w-72 ml-5'>
                        <Newsletter />
                    </div>
                </div>
            <div className='container mt-14'>
                <FeaturedCategory myArticles={hardware.edges} myCategory={'TVs'}/>
                <FeaturedCategory myArticles={brands.edges} myCategory={'Ring'} />
            </div>
			<Footer myMenu={navigationMenus} />
        </>
    )
}

export async function getStaticProps({ preview = false}) {
    const top = await getPropsForCategory('featured', 24)
    const hardware = await getPropsForCategory('tvs', 24)
	const brands = await getPropsForCategory('ring', 24)
	let navigationSlugs = [
		'brands',
		'faq',
		'entertainment',
		'in-the-home'
	]
	let navigationMenus = []
	let i = 0
	do {
		let res = await getMenuBySlug(navigationSlugs[i])
		navigationMenus.push(...res?.menus?.nodes)
		i++
	} while (i < navigationSlugs.length)

	return {
		props: {
			preview,
			top: top?.posts,
			hardware: hardware?.posts,
			brands: brands?.posts,
			navigationMenus: navigationMenus
		},
        revalidate: 1
	}
}
